### ISSUE TITLE
Some documentation links are broken

### ISSUE THREAD

**Issue by paolajuarezgomez** [oci-landing-zones/oracle-enterprise-landingzone#107]
https://github.com/oracle-quickstart/oci-landing-zones/blob/main/templates/enterprise-landing-zone/Architecture_Guide.md

Under Architecture Overview, check comparments, pages, Networking and connectivity, security ,etc

**Comment by gmackeig** [comment]
Fixed in https://github.com/oci-landing-zones/oracle-enterprise-landingzone/blob/main/Official_Documentation/OELZ_Baseline_Deployment/Architecture_Guide.md
